CREATE DATABASE Ontology

GO

USE Ontology

GO

CREATE TABLE [Patient]
(
    [PatientID] INT IDENTITY(1,1) NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
    [BirthDate] DATETIME2 NOT NULL DEFAULT(GETDATE()),
    [GenderTypeId] INT NOT NULL DEFAULT(0),
	[StatusID] INT NOT NULL DEFAULT(0),
	[StateID] INT  NOT NULL DEFAULT(0),
	CONSTRAINT [PK_Patient] PRIMARY KEY CLUSTERED ([PatientID] ASC)
)

GO

CREATE TABLE [Sign]
(
    [SignID] INT IDENTITY(1,1) NOT NULL,
	[StatusID] INT NOT NULL,
	[SignTypeID] INT NOT NULL,
	[Intensity] FLOAT(7) NOT NULL DEFAULT(0),
	CONSTRAINT [PK_Sign] PRIMARY KEY CLUSTERED ([SignID] ASC)
)

GO

CREATE TABLE [State]
(
    [StateID] INT IDENTITY(1,1) NOT NULL,
	[PreviousStateID] INT NOT NULL DEFAULT(0),
	[PatientID] INT NOT NULL,
	[StatusID] INT NOT NULL,
	[StateTypeID] INT NOT NULL,
	[PatientIntensity] FLOAT(7) NOT NULL DEFAULT(0),
	[CreatedDate] DATETIME2 NOT NULL DEFAULT(GETDATE()),
	CONSTRAINT [PK_State] PRIMARY KEY CLUSTERED ([StateID] ASC)
)

GO

CREATE TABLE [Status]
(
    [StatusID] INT IDENTITY(1,1) NOT NULL,
	[PatientID] INT NOT NULL,
	[PreviousStatusID] INT NOT NULL,
	[CreatedDate] DATETIME2 NOT NULL DEFAULT(GETDATE()),
	CONSTRAINT [PK_Status] PRIMARY KEY CLUSTERED ([StatusID] ASC)
)

GO


CREATE PROCEDURE [dbo].[uspClearData]
AS
BEGIN
	TRUNCATE TABLE Patient
	TRUNCATE TABLE [Sign]
	TRUNCATE TABLE [State]
	TRUNCATE TABLE [Status]
END;

GO